import time
import threading
import re
import ctypes
import pythoncom
import uiautomation as auto
from pynput import keyboard

# Only monitor genuine text input control types
ALLOWED_CONTROL_TYPES = {
    'EditControl',
    'DocumentControl'
}

# Windows desktop and shell windows to completely ignore
IGNORED_WINDOW_CLASSES = {
    'Progman',
    'WorkerW',
    'Shell_TrayWnd',
    'Shell_SecondaryTrayWnd'
}

def is_mojibake_or_corrupt(text: str) -> bool:
    """Detect if text contains typical GBK/UTF-8 mojibake, private-use, or control characters."""
    if not text:
        return True
    # Check for private-use area (often generated by mangled multi-byte sequences like \ue1e2)
    for ch in text:
        cp = ord(ch)
        if 0xE000 <= cp <= 0xF8FF:
            return True
        if cp == 0xFFFD:  # Replacement character
            return True
    return False

def contains_chinese(text: str) -> bool:
    if not text or is_mojibake_or_corrupt(text):
        return False
    return bool(re.search(r'[\u4e00-\u9fa5]', text))

def clean_input_text(text: str) -> str:
    if not text:
        return ""
    # Filter out replacement chars, nulls, and private-use characters
    cleaned = "".join(c for c in text if ord(c) < 0xE000 or ord(c) > 0xF8FF)
    cleaned = cleaned.replace('\ufffd', '').replace('\x00', '')
    return cleaned.strip()

def extract_latest_clause(text: str) -> str:
    """Extract the active sentence or clause from an input buffer."""
    text = clean_input_text(text)
    if not text or is_mojibake_or_corrupt(text):
        return ""
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    if not lines:
        return ""
    last_line = lines[-1]
    
    # Split by major punctuation
    parts = re.split(r'[。！？!?\n]', last_line)
    parts = [p.strip() for p in parts if p.strip()]
    if parts:
        target = parts[-1]
        if contains_chinese(target) and len(target) >= 2:
            return target
    if contains_chinese(last_line):
        return last_line[-60:]
    return ""

def get_clipboard_text() -> str:
    user32 = ctypes.windll.user32
    kernel32 = ctypes.windll.kernel32
    if not user32.OpenClipboard(0):
        return ""
    try:
        CF_UNICODETEXT = 13
        h_mem = user32.GetClipboardData(CF_UNICODETEXT)
        if not h_mem:
            return ""
        kernel32.GlobalLock.restype = ctypes.c_wchar_p
        ptr = kernel32.GlobalLock(h_mem)
        if ptr:
            text = str(ptr)
            kernel32.GlobalUnlock(h_mem)
            return clean_input_text(text)
    except Exception:
        pass
    finally:
        user32.CloseClipboard()
    return ""

class InputMonitor:
    def __init__(self, on_new_sentence_cb):
        self.on_new_sentence = on_new_sentence_cb
        self.running = False
        self.last_seen_text = ""
        self.active_buffer = ""
        self.last_change_time = 0
        self.last_emitted = ""
        self.debounce_seconds = 0.45
        
        # Double Ctrl tracking
        self.ctrl_down_time = 0
        self.last_pure_ctrl_tap = 0
        self.other_key_pressed_during_ctrl = False
        
        # Clipboard monitor
        self.last_clipboard = ""

    def start(self):
        self.running = True
        self.poll_thread = threading.Thread(target=self._poll_loop, daemon=True)
        self.poll_thread.start()

        self.hotkey_thread = threading.Thread(target=self._hotkey_loop, daemon=True)
        self.hotkey_thread.start()

    def stop(self):
        self.running = False

    def _get_focused_text(self) -> str:
        try:
            ctrl = auto.GetFocusedControl()
            if not ctrl:
                return ""
            
            # 1. STRICT CONTROL TYPE CHECK:
            # ONLY read text if user is actually focused on an input control (Edit or Document)
            ctrl_type = ctrl.ControlTypeName
            if ctrl_type not in ALLOWED_CONTROL_TYPES:
                return ""

            # 2. Check Top-Level Window: ignore Desktop, Taskbar, and our own Companion
            top = ctrl.GetTopLevelControl()
            if top:
                cls_name = getattr(top, 'ClassName', '')
                if cls_name in IGNORED_WINDOW_CLASSES:
                    return ""
                top_name = getattr(top, 'Name', '')
                if "EnglishCompanion" in top_name:
                    return ""

            # 3. Read text strictly through ValuePattern or TextPattern
            # ValuePattern (Standard for Edit, Web textareas, Input fields)
            try:
                vp = ctrl.GetPattern(auto.PatternId.ValuePattern)
                if vp and vp.Value:
                    val = clean_input_text(vp.Value)
                    if val and contains_chinese(val):
                        return val
            except Exception:
                pass

            # TextPattern (RichEdit, Word, Office, Document controls)
            try:
                tp = ctrl.GetPattern(auto.PatternId.TextPattern)
                if tp:
                    txt = clean_input_text(tp.DocumentRange.GetText(300))
                    if txt and contains_chinese(txt):
                        return txt
            except Exception:
                pass

            # NOTE: We intentionally NEVER fall back to ctrl.Name!
            # ctrl.Name of non-input elements contains icon names, window titles, and buttons,
            # which caused the desktop icon name to be wrongly captured.

        except Exception:
            pass
        return ""

    def _emit(self, text: str):
        text = clean_input_text(text)
        if not text or len(text) < 2 or text == self.last_emitted or not contains_chinese(text):
            return
        self.last_emitted = text
        threading.Thread(target=self.on_new_sentence, args=(text,), daemon=True).start()

    def _poll_loop(self):
        pythoncom.CoInitialize()
        try:
            while self.running:
                try:
                    current_text = self._get_focused_text()
                    now = time.time()

                    if current_text:
                        if current_text != self.last_seen_text:
                            self.last_seen_text = current_text
                            clause = extract_latest_clause(current_text)
                            if clause and contains_chinese(clause):
                                self.active_buffer = clause
                                self.last_change_time = now

                    # Check debounce: user paused typing for 450ms
                    if self.active_buffer and (now - self.last_change_time >= self.debounce_seconds):
                        to_send = self.active_buffer
                        self.active_buffer = ""
                        self._emit(to_send)

                    # Also check clipboard if user copied something
                    clip = get_clipboard_text()
                    if clip and clip != self.last_clipboard:
                        self.last_clipboard = clip
                        clip_clause = extract_latest_clause(clip)
                        if clip_clause and contains_chinese(clip_clause):
                            self._emit(clip_clause)

                except Exception:
                    pass

                time.sleep(0.3)
        finally:
            pythoncom.CoUninitialize()

    def _on_press(self, key):
        if key in (keyboard.Key.ctrl, keyboard.Key.ctrl_l, keyboard.Key.ctrl_r):
            self.ctrl_down_time = time.time()
            self.other_key_pressed_during_ctrl = False
        elif key == keyboard.Key.enter:
            # User pressed Enter: send message immediately
            if self.active_buffer:
                to_send = self.active_buffer
                self.active_buffer = ""
                self._emit(to_send)
        elif key == keyboard.Key.f8:
            # F8 Instant Learn
            self._trigger_instant()
        else:
            self.other_key_pressed_during_ctrl = True

    def _on_release(self, key):
        if key in (keyboard.Key.ctrl, keyboard.Key.ctrl_l, keyboard.Key.ctrl_r):
            now = time.time()
            if not self.other_key_pressed_during_ctrl and (now - self.ctrl_down_time < 0.25):
                if now - self.last_pure_ctrl_tap < 0.4:
                    self._trigger_instant()
                    self.last_pure_ctrl_tap = 0
                else:
                    self.last_pure_ctrl_tap = now

    def _trigger_instant(self):
        txt = self._get_focused_text()
        clause = extract_latest_clause(txt) if txt else ""
        if clause and contains_chinese(clause):
            self._emit(clause)
        else:
            clip = get_clipboard_text()
            if clip and contains_chinese(clip):
                self._emit(clip)

    def _hotkey_loop(self):
        with keyboard.Listener(on_press=self._on_press, on_release=self._on_release) as listener:
            listener.join()
